name: Swift

on:
  push:
    branches:
        - main
        - branch-*
  pull_request:
    branches:
        - main
        - branch-*

jobs:
  test:
    name: Build and test iOS app
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Force Xcode 13.2.1
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
    - name: Install Tools
      run: |
        brew install sonar-scanner
        gem install slather
        
        
        
        
        
